#!/bin/csh

#module load ifort
#module load compilers/intel/2016.10

set FC = ifort

# debug:
#set FFLAGS = '-debug -traceback -CB -align'
 
# run:
set FFLAGS = '-qopenmp -O2 -mp1 -ftz -align'

set GUIDE = guide
set LAPACK = mkl_lapack95_lp64
set BLAS = mkl_blas95_lp64
set MKL = mkl

set INCLUDEDIR = $MKLROOT/include/intel64/lp64/
set LIBDIR = $MKLROOT/lib/intel64/

#rm -f *.o *.mod

$FC $FFLAGS -I$INCLUDEDIR -c precision.f90
$FC $FFLAGS -I$INCLUDEDIR -c paramB_v4.f90
#$FC $FFLAGS -I$INCLUDEDIR -c ioibm-f90.f
$FC $FFLAGS -I$INCLUDEDIR -c mathlib.f
$FC $FFLAGS -I$INCLUDEDIR -c gaussquad.f90
#$FC $FFLAGS -I$INCLUDEDIR -c green_1-f90.f
$FC $FFLAGS -I$INCLUDEDIR -c mplane-1_v2.f90
$FC $FFLAGS -I$INCLUDEDIR -c mplane-2_v2.f
$FC $FFLAGS -I$INCLUDEDIR -c cintg2_v2.f
$FC $FFLAGS -I$INCLUDEDIR -c legacy_v3.f90
$FC $FFLAGS -I$INCLUDEDIR -c quadsym_v7.f90
$FC $FFLAGS -I$INCLUDEDIR -c onk3dk_v8.f90
$FC $FFLAGS -I$INCLUDEDIR -c bpart_v3.f90

$FC -o b2018.x precision.o paramB_v4.o mathlib.o gaussquad.o mplane-1_v2.o mplane-2_v2.o cintg2_v2.o legacy_v3.o quadsym_v7.o onk3dk_v8.o bpart_v3.o -L$LIBDIR -I$INCLUDEDIR -lmkl_intel_lp64 -l$BLAS -l$LAPACK -qmkl -lmkl_intel_thread -qopenmp -lm
